# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3b1b1f2107f809e14f81bf5ffeee1475bb51269e1b52d24245f56c68fe709933d5556382ae4c8b9e65850536deb0c1d50dcd19c77de0042d68e315cf41c0f34f

test:
  secret_key_base: 4b85f86f6d06e6d3770409606b6811983c67c063a7509716db2f3d4a784b32ffd079b840d07d03768a3f105ae951a4c5b1c86a24369bde7ed0e3653a8525bb92

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
